// LOCALHOST

###
GET http://localhost:3000/address

###
GET http://localhost:3000/address/

###
PUT http://localhost:3000/address/63e6a463fa6f9fcaedc02b17 HTTP/1.1
Content-Type: application/json

{
    "state":"Ohio"
}

###
POST http://localhost:3000/address HTTP/1.1
content-type: application/json

{
    "resident":"Simpson Family",
    "number":"742",
    "street":"Evergreen Terrace",
    "unit":"N/A",
    "city":"Springfield",
    "state":"Oregon",
    "country":"USA",
    "zip":"97403"
}

###
DELETE http://localhost:3000/address/63e6abc635ed3c524dfa4411 HTTP/1.1

// RENDER
###
GET https://addressbook-iyzx.onrender.com/address

###
POST https://addressbook-iyzx.onrender.com/address HTTP/1.1
content-type: application/json

{
    "resident":"Simpson Family",
    "number":"742",
    "street":"Evergreen Terrace",
    "unit":"N/A",
    "city":"Springfield",
    "state":"Oregon",
    "country":"USA",
    "zip":"97403"
}
